import os
import logging
from datetime import date

import resend

logger = logging.getLogger(__name__)

# IST is UTC+5:30
_IST_OFFSET_HOURS = 5
_IST_OFFSET_MINS = 30


def _utc_to_ist(hour_utc: int, min_utc: int) -> str:
    total_mins = hour_utc * 60 + min_utc + _IST_OFFSET_HOURS * 60 + _IST_OFFSET_MINS
    h = (total_mins // 60) % 24
    m = total_mins % 60
    suffix = "AM" if h < 12 else "PM"
    h12 = h % 12 or 12
    return f"{h12}:{m:02d} {suffix} IST"


def _theme_block(idx: int, theme: dict, tweet: dict, content: dict) -> str:
    post_time = _utc_to_ist(theme.get("post_hour_utc", 0), theme.get("post_min_utc", 30))
    tweet_text = tweet.get("text", "").replace("\n", "<br>")
    post_content = content.get("content", "").replace("\n", "<br>")
    reply_content = content.get("reply", "").replace("\n", "<br>")

    return f"""
    <div style="margin-bottom:40px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;font-family:sans-serif;">
      <div style="background:#1a1a2e;color:#fff;padding:16px 20px;display:flex;align-items:center;gap:10px;">
        <span style="font-size:22px;">{theme.get('emoji','')}</span>
        <div>
          <div style="font-size:16px;font-weight:700;">{idx}. {theme.get('name','')}</div>
          <div style="font-size:12px;color:#a0aec0;">Post at {post_time}</div>
        </div>
      </div>

      <div style="padding:16px 20px;background:#f9fafb;">
        <div style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:6px;">Source Tweet</div>
        <div style="font-size:13px;color:#374151;margin-bottom:6px;">@{tweet.get('author','')} &nbsp;·&nbsp;
          <span style="color:#10b981;">❤ {tweet.get('likes',0):,}</span> &nbsp;·&nbsp;
          <span style="color:#6366f1;">👁 {tweet.get('views',0):,}</span>
        </div>
        <div style="font-size:13px;color:#1f2937;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:12px;margin-bottom:8px;">{tweet_text}</div>
        <a href="{tweet.get('url','')}" style="font-size:12px;color:#3b82f6;">View original tweet ↗</a>
      </div>

      <div style="padding:16px 20px;border-top:1px solid #e5e7eb;">
        <div style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px;">Ready to Post</div>
        <div style="font-size:13px;color:#1f2937;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:12px;white-space:pre-wrap;">{post_content}</div>
      </div>

      <div style="padding:16px 20px;border-top:1px solid #e5e7eb;">
        <div style="font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px;">Reply (Sources)</div>
        <div style="font-size:13px;color:#1f2937;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:12px;white-space:pre-wrap;">{reply_content}</div>
      </div>
    </div>
    """


def send_digest(results: list[dict]):
    """
    results: list of dicts with keys: theme, tweet, content
    """
    resend.api_key = os.environ["RESEND_API_KEY"]
    to_email = os.environ["DIGEST_TO_EMAIL"]
    today = date.today().strftime("%B %d, %Y")

    blocks = "".join(
        _theme_block(i + 1, r["theme"], r["tweet"], r["content"])
        for i, r in enumerate(results)
    )

    html = f"""
    <!DOCTYPE html>
    <html>
    <body style="margin:0;padding:24px;background:#f3f4f6;font-family:sans-serif;">
      <div style="max-width:680px;margin:0 auto;">
        <div style="text-align:center;margin-bottom:32px;">
          <h1 style="font-size:24px;font-weight:800;color:#1a1a2e;margin:0;">📰 Wise Brief</h1>
          <p style="color:#6b7280;margin:4px 0 0;">Daily Content Digest — {today}</p>
          <p style="color:#9ca3af;font-size:12px;margin:4px 0 0;">{len(results)} themes ready to schedule in Buffer</p>
        </div>
        {blocks}
        <div style="text-align:center;color:#9ca3af;font-size:11px;margin-top:24px;">
          Generated by Wise Brief · Schedule these in Buffer at the times above
        </div>
      </div>
    </body>
    </html>
    """

    resend.Emails.send({
        "from": "Wise Brief <onboarding@resend.dev>",
        "to": [to_email],
        "subject": f"Wise Brief Digest — {today} ({len(results)} posts ready)",
        "html": html,
    })
    logger.info(f"Digest email sent to {to_email} with {len(results)} themes.")
